apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-admin-deployment
  labels:
    app: login-admin
spec:
  # Keeps 2 copies of your website running at all times for high availability
  replicas: 2 
  selector:
    matchLabels:
      app: login-admin
  template:
    metadata:
      labels:
        app: login-admin
    spec:
      containers:
      - name: login-admin-container
        # Name of your Docker image built by Jenkins
        image: login-admin-project:latest 
        # Uses the local Docker image if it already exists on the server
        imagePullPolicy: IfNotPresent 
        ports:
        # The internal port that Apache HTTP server listens on (from your EXPOSE 80)
        - containerPort: 80 
---
apiVersion: v1
kind: Service
metadata:
  name: login-admin-service
spec:
  # NodePort exposes the service outside the cluster on a specific port of the server
  type: NodePort 
  selector:
    app: login-admin
  ports:
    # The internal port used by the Kubernetes cluster service
    - port: 80         
      # The target port on the container where traffic is sent
      targetPort: 80   
      # The external port used to access your website from a browser (Configured to 30000)
      nodePort: 30000  

